



spring:


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.100.145.226:3306/yhsx2.0?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: yhsx123456

logging:
  path: /mysvn/yhsx/target
  file: yhsx.log